[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if add and not G.GAME.banned_keys[v.key] then "
position = "after"
match_indent = true
payload = '''


if (G.GAME.selected_back_key or {}).key == "b_rgl_pinkdeck" then
    -- print("pink deck online")
    if v.key:find('j_rgl_') then
        -- print("Boosting joker:", v.key)
        for i = 1, 4 do
            _pool[#_pool + 1] = v.key
            _pool_size = _pool_size + 1
        end
    end
end
'''